version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: dramabang-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - DB_DRIVER=postgres
      - DB_HOST=postgres
      - DB_USER=dramabang
      - DB_PASSWORD=dramabang
      - DB_NAME=dramabang
      - DB_PORT=5432
      - TZ=Asia/Jakarta
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=cs.dramaplay@gmail.com
      - SMTP_PASS=vhitxtasgonysxdp
      - SMTP_SENDER=DramaPlay <cs.dramaplay@gmail.com>
    volumes:
      - ./data:/app/data
      - ./uploads:/app/public/uploads
    depends_on:
      - postgres
    networks:
      - dramabang-net

  postgres:
    image: postgres:15-alpine
    container_name: dramabang-postgres
    restart: always
    environment:
      POSTGRES_USER: dramabang
      POSTGRES_PASSWORD: dramabang
      POSTGRES_DB: dramabang
      TZ: Asia/Jakarta
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dramabang-net

  frontend:
    build:
      context: ./frontend
    container_name: dramabang-frontend
    restart: always
    environment:
      - INTERNAL_API_URL=http://backend:3000/api
    depends_on:
      - backend
    networks:
      - dramabang-net

  nginx:
    image: nginx:alpine
    container_name: dramabang-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dramabang-net

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: dramabang-tunnel
    restart: always
    volumes:
      - ./data:/data
    command: tunnel run --token-file /data/tunnel_token
    networks:
      - dramabang-net

networks:
  dramabang-net:
    driver: bridge
